import Link from 'next/link'
import { ArrowRight, CheckCircle2, Mail, MessageCircle, Phone } from 'lucide-react'
import ContactForm from '@/components/contact-form'
import { InfoPageShell, InfoCta, ArticleSection } from '@/components/info-page-shell'
import { contactConfig } from '@/lib/contact'

export const metadata = { title: 'Contact ReorderIQ', description: 'Talk to ReorderIQ about repeat revenue, pricing, integrations, and customer reorder opportunities.' }

export default function ContactPage() {
  return <InfoPageShell eyebrow="CONTACT US" title="Let’s Talk About Your Repeat Revenue" description="Have questions about ReorderIQ, pricing, integrations, or how it could work for your business? Send us a message and our team will get back to you.">
    <div className="grid gap-8 lg:grid-cols-[.78fr_1.22fr] lg:items-start"><div className="space-y-6"><div><h2 className="text-2xl font-bold tracking-tight">Choose the easiest way to reach us.</h2><p className="mt-3 text-sm leading-7 text-slate-600">Whether you are exploring the product or already using ReorderIQ, we are here to help you understand the next step.</p></div><div className="space-y-3"><a href={`mailto:${contactConfig.email}`} className="flex items-start gap-3 rounded-2xl bg-white p-4 shadow-soft transition hover:shadow-lift"><Mail className="mt-0.5 text-emerald-700" size={19} /><span><span className="block text-sm font-semibold text-slate-900">Email</span><span className="mt-1 block text-sm text-slate-600">{contactConfig.email}</span></span></a><a href={contactConfig.phoneHref} className="flex items-start gap-3 rounded-2xl bg-white p-4 shadow-soft transition hover:shadow-lift"><Phone className="mt-0.5 text-emerald-700" size={19} /><span><span className="block text-sm font-semibold text-slate-900">Phone</span><span className="mt-1 block text-sm text-slate-600">{contactConfig.phoneDisplay}</span></span></a><a href={contactConfig.whatsappHref} target="_blank" rel="noreferrer" className="flex items-start gap-3 rounded-2xl bg-white p-4 shadow-soft transition hover:shadow-lift"><MessageCircle className="mt-0.5 text-emerald-700" size={19} /><span><span className="block text-sm font-semibold text-slate-900">WhatsApp</span><span className="mt-1 block text-sm text-slate-600">+254 727 876 632</span></span></a></div><div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="font-semibold">Tell Us About Your Business</p><p className="mt-2 text-sm leading-6 text-slate-300">The more we understand about your business, customers, and purchasing cycles, the better we can understand how ReorderIQ could fit into your workflow.</p></div></div><div className="surface p-5 sm:p-7"><h2 className="text-xl font-bold tracking-tight">Send us a message</h2><p className="mt-2 mb-6 text-sm text-slate-500">Required fields are marked with an asterisk.</p><ContactForm /></div></div>
    <ArticleSection title="How can we help?"><div className="grid gap-4 md:grid-cols-3"><div className="well p-5"><h3 className="font-semibold text-slate-900">Product Demo</h3><p className="mt-2 text-sm leading-6 text-slate-600">Want a walkthrough of ReorderIQ for your business?</p><a href={`mailto:${contactConfig.email}`} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-emerald-700">Request a Demo <ArrowRight size={14} /></a></div><div className="well p-5"><h3 className="font-semibold text-slate-900">Pricing</h3><p className="mt-2 text-sm leading-6 text-slate-600">Have questions about plans or custom pricing?</p><Link href="/pricing" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-emerald-700">View Pricing <ArrowRight size={14} /></Link></div><div className="well p-5"><h3 className="font-semibold text-slate-900">Existing Customer</h3><p className="mt-2 text-sm leading-6 text-slate-600">Already using ReorderIQ and need assistance?</p><a href={`mailto:${contactConfig.email}`} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-emerald-700">Contact Support <ArrowRight size={14} /></a></div></div></ArticleSection>
    <div className="grid gap-4 rounded-3xl bg-emerald-500/10 p-6 sm:grid-cols-2"><div><h2 className="text-xl font-bold tracking-tight text-slate-950">A practical conversation, not a sales script.</h2><p className="mt-3 text-sm leading-6 text-slate-700">We focus on clear communication, business-focused product support, practical implementation, and a data-conscious approach.</p></div><div className="grid gap-3 text-sm font-semibold text-slate-800 sm:grid-cols-2">{['Clear communication', 'Business-focused support', 'Practical implementation', 'Data-conscious approach'].map((item) => <span key={item} className="flex items-center gap-2"><CheckCircle2 className="text-emerald-700" size={17} />{item}</span>)}</div></div>
    <InfoCta />
  </InfoPageShell>
}
