import Link from 'next/link'
import { ArrowLeft, ArrowRight } from 'lucide-react'

export function InfoPageShell({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <main className="min-h-screen bg-canvas text-slate-950"><header className="sticky top-0 z-40 bg-canvas/85 shadow-header backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-2 text-lg font-bold tracking-tight"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-700 text-sm text-white">R</span>ReorderIQ</Link><nav className="hidden items-center gap-5 text-sm text-slate-600 lg:flex"><Link href="/#product">Product</Link><Link href="/#how-it-works">How It Works</Link><Link href="/#features">Features</Link><Link href="/pricing">Pricing</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></nav><div className="flex items-center gap-3"><Link href="/sign-in" className="hidden text-sm font-semibold text-slate-600 sm:block">Log in</Link><Link href="/sign-up" className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800">Get Started</Link></div></div></header><section className="bg-white"><div className="mx-auto max-w-4xl px-5 py-16 lg:px-8 lg:py-20"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-700"><ArrowLeft size={15} /> Back to ReorderIQ</Link><p className="mt-10 text-sm font-semibold text-emerald-700">{eyebrow}</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{description}</p></div></section><div className="mx-auto max-w-4xl px-5 py-12 lg:px-8 lg:py-16">{children}</div><footer className="bg-white"><div className="mx-auto flex max-w-4xl flex-col gap-4 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© 2026 ReorderIQ. All rights reserved.</span><div className="flex gap-4"><Link href="/faq" className="hover:text-emerald-700">FAQ</Link><Link href="/documentation" className="hover:text-emerald-700">Documentation</Link><Link href="/privacy" className="hover:text-emerald-700">Privacy</Link><Link href="/cookies" className="hover:text-emerald-700">Cookies</Link></div></div></footer></main>
}

export function InfoCallout({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl bg-emerald-500/10 p-5"><p className="font-semibold text-emerald-900">{title}</p><div className="mt-2 text-sm leading-6 text-emerald-900/75">{children}</div></div> }

export function InfoCta() { return <div className="mt-12 rounded-2xl bg-slate-950 p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-8 sm:p-8"><div><p className="font-semibold">Ready to turn repeat behavior into revenue?</p><p className="mt-2 text-sm text-slate-300">Create your workspace and turn customer order history into repeat sales.</p></div><Link href="/sign-up" className="mt-5 inline-flex shrink-0 items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-emerald-400 sm:mt-0">Get Started <ArrowRight size={15} /></Link></div> }

export function ArticleSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-10 first:mt-0"><h2 className="text-2xl font-bold tracking-tight">{title}</h2><div className="mt-4 space-y-4 text-sm leading-7 text-slate-600">{children}</div></section> }
