import { InfoCallout, InfoCta, InfoPageShell } from '@/components/info-page-shell'

const categories = ['Getting Started', 'ReorderIQ', 'Reorder Predictions', 'Customer Data', 'Integrations', 'Subscriptions & Billing', 'Payments', 'Security & Privacy']
const faqs = [
  ['Getting Started', 'What is ReorderIQ?', 'ReorderIQ is a customer retention and repeat-revenue platform that analyzes customer purchase history to identify customers who may be ready to reorder.'],
  ['Getting Started', 'Who is ReorderIQ for?', 'ReorderIQ is designed for businesses with repeat customers that want to turn existing customer and order data into timely follow-up opportunities.'],
  ['Getting Started', 'How do I get started?', 'Create an account, connect your customer and order data, and ReorderIQ will begin organizing your repeat-purchase opportunities.'],
  ['ReorderIQ', 'What does ReorderIQ help my team do?', 'It gives your team one place to understand customer behavior, prioritize outreach, and estimate the revenue available from customers likely to buy again.'],
  ['Reorder Predictions', 'How are reorder predictions calculated?', 'Predictions use purchase cadence, recency, order frequency, customer value, and product behavior. They are decision-support signals, not guarantees.'],
  ['Reorder Predictions', 'Can I see why a customer is prioritized?', 'Yes. Each opportunity includes signals such as reorder likelihood, last order, average order value, and estimated next purchase timing.'],
  ['Customer Data', 'What data can I connect?', 'ReorderIQ is designed around customer profiles, orders, order dates, products, quantities, and values. The exact import options depend on your plan and integration.'],
  ['Integrations', 'Does ReorderIQ integrate with my tools?', 'ReorderIQ supports structured customer and order data and is designed to connect with commerce, CRM, and messaging workflows. Contact us about your stack.'],
  ['Subscriptions & Billing', 'Can I change plans?', 'Yes. You can move between plans from the billing area. Changes are reflected according to the billing terms shown at checkout.'],
  ['Payments', 'Which payment methods are supported?', 'Checkout is designed for card and local payment methods, including M-Pesa and Paystack where enabled for your account.'],
  ['Security & Privacy', 'Who owns my customer data?', 'You retain ownership of your business data. ReorderIQ uses it to provide the service and applies access controls designed for business applications.'],
]

export default function FAQPage() { return <InfoPageShell eyebrow="Help center" title="Frequently Asked Questions" description="Everything you need to know about ReorderIQ, subscriptions, reorder predictions, integrations, and getting started."><div className="surface p-4"><label htmlFor="faq-search" className="sr-only">Search questions</label><input id="faq-search" placeholder="Search questions..." className="field w-full px-4 py-3 text-sm" /></div><div className="mt-8 flex flex-wrap gap-2">{categories.map((category) => <a key={category} href={`#${category.toLowerCase().replaceAll(' ', '-')}`} className="rounded-full bg-wash px-3.5 py-1.5 text-xs font-semibold text-slate-600 transition hover:bg-wash-strong hover:text-slate-900">{category}</a>)}</div><div className="mt-12 space-y-12">{categories.map((category) => { const items = faqs.filter(([group]) => group === category); return <section key={category} id={category.toLowerCase().replaceAll(' ', '-')}><h2 className="text-2xl font-bold tracking-tight">{category}</h2><div className="mt-4 space-y-3">{items.map(([, question, answer]) => <details key={question} className="surface group px-5 py-4"><summary className="cursor-pointer list-none pr-6 font-semibold text-slate-900 marker:hidden">{question}<span className="float-right text-emerald-700">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></section> })}</div><InfoCallout title="Still have a question?">Reach out to hello@reorderiq.com and tell us what you are trying to accomplish.</InfoCallout><InfoCta /></InfoPageShell> }
